### ISSUE TITLE
Would you be interested in moving this to Masterminds?

### ISSUE THREAD

**Issue by technosophos** [Masterminds/goutils#19]
Hey Alex!

We've been working on building up a bunch of high-quality Go libraries under the https://github.com/Masterminds project. This is one of the libraries that I still use a lot, and I was wondering if you'd like to join the Masterminds organization with this project. @mattfarina and I would like to help maintain and publicize it.

If not, that's cool. We won't be offended.

Matt

**Comment by aokoli** [comment]
Hi Matt! 

Long time no speak! I actually thought of you recently (earlier in the day). Sure thing -- I'll be glad to join the Masterminds project with goutils. Just let me know if there is anything else you will need from my end. I hope all is great out there, and hopefully we can catch up sometime.

Thanks,

Alex

**Comment by technosophos** [comment]
Alex,

That is fabulous news! As to the mechanics of it, I think all you need to do is go to Settings and do the Transfer thing. I already sent you an invite to join the org. We should definitely catch up some time. I'd love to hear how things are going on your end.

Matt

**Comment by aokoli** [comment]
Hello Matt,

Sounds great! I attempted the transfer, and there may be a permission issue.

I get this error,
![image](https://cloud.githubusercontent.com/assets/2807956/23959674/ca3948bc-0973-11e7-9d8f-74b4d128818d.png)


While using these transfer inputs,
![image](https://cloud.githubusercontent.com/assets/2807956/23959463/438fda74-0973-11e7-81ed-4230ac6f6ea8.png)

I already accepted the Masterminds invitation you sent earlier.

Thanks,

Alex

**Comment by technosophos** [comment]
Oh, there was another check box to check to allow team members to create new repos. Sorry about that. Fixed now.

**Comment by aokoli** [comment]
Nice -- transfer has been completed! @technosophos

**Comment by technosophos** [comment]
I just set you as admin on the project, @aokoli. I'm going to close this issue since I think we're all done. Thanks again!
